### PR TITLE
Add previous and next revision nav links to Changes view

### LINKED ISSUE #174: Mention “previous“ commit in report
When looking at a report, it is often not clear what commit the changes are relative to, especially when codespeed can get confused (#173). In order to debug that better, and also generally it would be nice to have that in the report.

Bonus points if it can be used for navigation. I could imagine two columns: One for the previous report (with summary), and one for the following (also with summary), if available. (Please ask if I did not make myself clear.)

### PR DESCRIPTION
**Pull request by str4d**
Closes #174

### CODE REVIEW

**Review by tobami — CHANGES_REQUESTED** [review]
This breaks when selecting a commit which has links to both previous and next.

Also the links could be a bit smaller to be easier on the eyes :-)

**Comment by str4d** [comment]
> This breaks when selecting a commit which has links to both previous and next.

Could you describe how it breaks? It was working for me last I checked, but then I did go through several rounds of breaking and fixing the JS. I did find I had to hard-refresh every time to get the correct code running.

> Also the links could be a bit smaller to be easier on the eyes :-)

Agreed, and some space between them and the table would be good too. I will play with some CSS.

**Comment by tobami** [comment]
I loaded the fixtures (`./manage.py loaddata codespeed/fixtures/testdata.json`). It has 3 commits in a branch, when accessing the middle one the backend crashes.

**Comment by str4d** [comment]
Thanks! Good to have a secondary dataset with different data :smile:

Force-pushed to address both comments.

**Comment by str4d** [comment]
The problem was that I was trying to select a unique Report to get a summary string from, but had forgotten to select over the entire `unique_together` set of keys :sweat_smile:

**Review by tobami — APPROVED** [review]

**Pull request merged**
