### PR TITLE
Some modernization of the UI

### PR DESCRIPTION
**Pull request by javierhonduco**
Several visual improvements have been done in this PR.
Most of them are tiny but they make the experience of using `codespeed` significantly better IMO.
* Modernized visuals related to the `border-radius` attribute.
* Move on to `html5`.
* Usage of `Arial` as the default font.
* Removal of some images such as the background one and the loading gif and the warning sign that has been replaced by its unicode counterpart.
* Shadow removal from mosts graphs. The ones from bars and container boxes.
* Added some `vim` and OSX-specific files to be ignored.

Things I haven't been able to do and that I would love to have (and if I have some spare time I'll try to do):
* Get rid of **all** shadows in graphs and use a consistent font for titles and legends.
* Replace the current graph library with a more modern one with a nicer API. Not easy at all, but I think it would pay off.
* JS refactor. (Don't think I'm skilled enough js-wise, but still)
* Substitute all images with other assets.

Thank you for the project 💟,

### CODE REVIEW

**Comment by tobami** [comment]
Nice improvements all around! I agree the look was getting really old, this helps a log, many thanks!

I was thinking along the same lines as you: modernize the design, replace the plotting library, refactor JS and so on. If you want to do any of those that would be great. Which graph library do you have in mind?

**Comment by javierhonduco** [comment]
It's just a tiny little bit, but glad you liked it. 😄 

Yeah, I would love being to work on those things, but ATM cannot work fulltime on that. Will try to contribute with small changes instead.
Probably for the plotting library could be something based on `d3`? I've seen many that are really nice, complete and have a interesting and simple API. 

Another feature that just popped to my mind would be having a realtime feature that alerted you when some new datapoint is introduced, like the one GitHub has whenever a new branch or commits are pushed, but of course that is not trivial to implement in a good way.

**Comment by tobami** [comment]
Hi Javier,

D3 would be a good pick yes. As to the "feature that alerted", you mean
pushing to some webhook, or email notifications? Doesn't RSS work for you?

Small changes are great! You don't need big contributions in order for it
to be helpful.
Btw. may I ask what you are using Codespeed for?

**Comment by javierhonduco** [comment]
It would be nice to have those notifications for when you are viewing a benchmark and it's updated but you are still viewing former results. 
Just as a heads up that tells you that new data has arrived.
So it's a different use case from RSS, I'd say :).

It's one of the tools that I was having a look to use for my bachelor thesis, as performance is a key aspect.

**Pull request merged**
